server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/bjseoul?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: bjseoul
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: rksel0712
    password: mmfm nfpc vxud ooyn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 10MB
      file-size-threshold: 100MB
      location: ${java.io.tmpdir}

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml


#logging:
#  level:
#    org.mybatis: DEBUG
#    org.mybatis.spring: DEBUG
#    org.apache.ibatis: DEBUG
#    org.springframework.web: DEBUG
#    jdbc.sqlonly: DEBUG
#    jdbc.sqltiming: DEBUG
#    jdbc.resultset: DEBUG
#    jdbc.audit: DEBUG